name: CI for doordash

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # This action clones the content of the current repo into the remote runner
      - name: Build Docker Image
        run: docker build -t app .
      - name: Run the container
        run:  |
          docker run -d \
          --name app \
          -p 8080:8090 \
          app
      - name: Wait for the app
        run: |
          timeout 60s bash -c '
            until curl -fsS http://localhost:8080/status; do
              echo "Waiting for app..."
              sleep 2
            done
          '
      - name: Install deps
        run: pip install pytest httpx
      - name: Run tests
        run: pytest -v
